# Generated by Django 3.2 on 2024-10-04 17:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Subject', '0001_initial'),
        ('Student', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PointSj',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pointsj_dcc', models.FloatField(null=True)),
                ('pointsj_exam', models.FloatField(null=True)),
                ('student_id', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='Student.student')),
                ('subject_id', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='Subject.subject')),
            ],
            options={
                'unique_together': {('student_id', 'subject_id')},
            },
        ),
    ]
