# Generated by Django 3.2 on 2024-10-04 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('std_id', models.AutoField(primary_key=True, serialize=False)),
                ('std_msv', models.CharField(max_length=191)),
                ('std_name', models.CharField(max_length=20)),
                ('std_year', models.DateField(verbose_name='Ngày sinh')),
                ('std_address', models.CharField(max_length=191)),
                ('std_gender', models.CharField(max_length=10)),
            ],
        ),
    ]
