# Generated by Django 3.2 on 2024-10-04 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('subject_id', models.AutoField(primary_key=True, serialize=False)),
                ('subject_msj', models.CharField(max_length=50)),
                ('subject_name', models.CharField(max_length=50)),
                ('subject_tc', models.IntegerField(null=True)),
            ],
        ),
    ]
